"use client";

import { FormEvent, useEffect as reactUseEffect, useState } from "react";
import { AdminShell } from "@/features/admin/admin-shell";
import { apiRequest, getApiErrorMessage } from "@/lib/api-client";
import { formatPrice } from "@/lib/format";
import { changeMessageStatus, changeOrderStatus, getCustomers, getMessages, getOrders, getPromotions, getShippingRules, type AdminCustomer, type AdminOrder, type ContactMessage, type Promotion, type ShippingRule } from "@/features/admin/store-api";

function useEffect(effect: () => void | Promise<void>, dependencies: unknown[]) { reactUseEffect(() => { void effect(); }, dependencies); }

export function AdminOrdersPage() { const [items, setItems] = useState<AdminOrder[]>([]); const [error, setError] = useState<string>(); const load = () => getOrders().then(setItems).catch((e) => setError(getApiErrorMessage(e))); useEffect(load, []); async function update(id:string,status:string){try{await changeOrderStatus(id,status);load();}catch(e){setError(getApiErrorMessage(e));}} return <AdminShell title="سفارش‌ها"><PageError error={error}/><div className="admin-panel admin-table-wrap"><table className="admin-table"><thead><tr><th>شماره</th><th>مشتری</th><th>تلفن</th><th>مبلغ</th><th>وضعیت</th><th>تاریخ</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td dir="ltr">{x.number}</td><td>{x.customerName}</td><td dir="ltr">{x.phone}</td><td>{formatPrice(x.total)}</td><td><select value={x.status} onChange={e=>update(x.id,e.target.value)} aria-label={`وضعیت سفارش ${x.number}`}><option value="PendingConfirmation">در انتظار بررسی</option><option value="Confirmed">تأیید شده</option><option value="Preparing">در حال آماده‌سازی</option><option value="Shipped">ارسال شده</option><option value="Delivered">تحویل شده</option><option value="Cancelled">لغو شده</option><option value="Expired">منقضی شده</option></select></td><td>{new Intl.DateTimeFormat("fa-IR",{dateStyle:"medium"}).format(new Date(x.createdAt))}</td></tr>)}</tbody></table>{items.length===0&&<Empty text="هنوز سفارشی ثبت نشده است."/>}</div></AdminShell>; }

export function AdminCustomersPage() { const [items,setItems]=useState<AdminCustomer[]>([]); const [error,setError]=useState<string>(); useEffect(()=>{getCustomers().then(setItems).catch(e=>setError(getApiErrorMessage(e)));},[]); return <AdminShell title="مشتریان"><PageError error={error}/><div className="admin-panel admin-table-wrap"><table className="admin-table"><thead><tr><th>نام</th><th>تلفن</th><th>ایمیل</th><th>تعداد سفارش</th><th>ارزش سفارش‌ها</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.fullName}</td><td dir="ltr">{x.phone}</td><td dir="ltr">{x.email??"—"}</td><td>{x.orderCount}</td><td>{formatPrice(x.totalOrderValue)}</td></tr>)}</tbody></table>{items.length===0&&<Empty text="مشتری‌ای ثبت نشده است."/>}</div></AdminShell>; }

export function AdminMessagesPage() { const [items,setItems]=useState<ContactMessage[]>([]); const [error,setError]=useState<string>(); const load=()=>getMessages().then(setItems).catch(e=>setError(getApiErrorMessage(e))); useEffect(load,[]); async function update(id:string,status:string){try{await changeMessageStatus(id,status);load();}catch(e){setError(getApiErrorMessage(e));}} return <AdminShell title="پیام‌های مشتریان"><PageError error={error}/><div className="admin-panel admin-table-wrap"><table className="admin-table"><thead><tr><th>فرستنده</th><th>موضوع</th><th>پیام</th><th>وضعیت</th><th>تاریخ</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.name}<small dir="ltr">{x.phone}</small></td><td>{x.topic}</td><td className="admin-table__message">{x.body}</td><td><select value={x.status} onChange={e=>update(x.id,e.target.value)} aria-label={`وضعیت پیام ${x.topic}`}><option value="New">جدید</option><option value="Read">خوانده‌شده</option><option value="Replied">پاسخ‌داده‌شده</option><option value="Archived">بایگانی</option></select></td><td>{new Intl.DateTimeFormat("fa-IR",{dateStyle:"medium"}).format(new Date(x.createdAt))}</td></tr>)}</tbody></table>{items.length===0&&<Empty text="پیامی وجود ندارد."/>}</div></AdminShell>; }

export function AdminPromotionsPage() { const [items,setItems]=useState<Promotion[]>([]); const [error,setError]=useState<string>(); const load=()=>getPromotions().then(setItems).catch(e=>setError(getApiErrorMessage(e))); useEffect(load,[]); async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await apiRequest("/api/admin/promotions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),code:f.get("code")||null,type:"Coupon",discountType:"Percentage",value:Number(f.get("value")),startsAtUtc:new Date().toISOString(),isActive:true})});e.currentTarget.reset();load();}catch(e){setError(getApiErrorMessage(e));}} return <AdminShell title="تخفیف‌ها"><PageError error={error}/><div className="admin-two-col"><form className="admin-panel admin-form" onSubmit={submit}><h2>کد تخفیف جدید</h2><label className="form-field">عنوان<input name="name" required /></label><label className="form-field">کد<input name="code" required dir="ltr" /></label><label className="form-field">درصد تخفیف<input name="value" type="number" min="1" max="100" required /></label><button className="button button--primary" type="submit">افزودن تخفیف</button></form><div className="admin-panel admin-table-wrap"><table className="admin-table"><thead><tr><th>عنوان</th><th>کد</th><th>مقدار</th><th>مصرف</th><th>وضعیت</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.name}</td><td dir="ltr">{x.code??"خودکار"}</td><td>{x.discountType==="Percentage"?`${x.value}%`:formatPrice(x.value)}</td><td>{x.usageCount}{x.usageLimit?` / ${x.usageLimit}`:""}</td><td>{x.isActive?"فعال":"غیرفعال"}</td></tr>)}</tbody></table></div></div></AdminShell>; }

export function AdminShippingPage() { const [items,setItems]=useState<ShippingRule[]>([]); const [error,setError]=useState<string>(); const load=()=>getShippingRules().then(setItems).catch(e=>setError(getApiErrorMessage(e))); useEffect(load,[]); async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await apiRequest("/api/admin/shipping-rules",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),province:f.get("province")||null,city:f.get("city")||null,cost:Number(f.get("cost")),priority:Number(f.get("priority")),isActive:true})});e.currentTarget.reset();load();}catch(e){setError(getApiErrorMessage(e));}} return <AdminShell title="قوانین ارسال"><PageError error={error}/><div className="admin-two-col"><form className="admin-panel admin-form" onSubmit={submit}><h2>قانون ارسال جدید</h2><label className="form-field">عنوان<input name="name" required /></label><label className="form-field">استان<input name="province" /></label><label className="form-field">شهر<input name="city" /></label><label className="form-field">هزینه<input name="cost" type="number" min="0" required /></label><label className="form-field">اولویت<input name="priority" type="number" defaultValue="10" required /></label><button className="button button--primary" type="submit">افزودن قانون</button></form><div className="admin-panel admin-table-wrap"><table className="admin-table"><thead><tr><th>عنوان</th><th>محدوده</th><th>هزینه</th><th>اولویت</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.name}</td><td>{[x.province,x.city].filter(Boolean).join("، ")||"همه"}</td><td>{formatPrice(x.cost)}</td><td>{x.priority}</td></tr>)}</tbody></table></div></div></AdminShell>; }

function PageError({error}:{error?:string}){return error?<div className="admin-alert admin-alert--error" role="alert">{error}</div>:null} function Empty({text}:{text:string}){return <div className="admin-empty">{text}</div>}
